# Generated by Django 4.0.7 on 2022-08-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'apvl_mt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, max_length=4000, null=True)),
                ('confidential', models.BooleanField(blank=True, default=False)),
                ('jira_temp', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'doc_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, max_length=4000, null=True)),
                ('spec_one', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('ver', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=4000)),
                ('keywords', models.CharField(blank=True, max_length=4000, null=True)),
                ('state', models.CharField(max_length=50)),
                ('create_dt', models.DateTimeField()),
                ('mod_ts', models.DateTimeField()),
                ('jira', models.CharField(blank=True, max_length=4000, null=True)),
                ('anon_access', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='spec.department')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='spec.doctype')),
            ],
            options={
                'db_table': 'spec',
                'managed': True,
                'unique_together': {('num', 'ver')},
            },
        ),
        migrations.CreateModel(
            name='SpecReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('ver', models.CharField(blank=True, max_length=50, null=True)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='spec.spec')),
            ],
            options={
                'db_table': 'spec_reference',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpecHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_ts', models.DateTimeField()),
                ('change_type', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=4000)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist', to='spec.spec')),
                ('upd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spec_hist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='spec.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DepartmentReadRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readRoles', to='spec.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.role')),
            ],
            options={
                'db_table': 'dept_read_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApprovalMatrixSignRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apvl_mt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signRoles', to='spec.approvalmatrix')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.role')),
            ],
            options={
                'db_table': 'apvl_mt_sign_role',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='approvalmatrix',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='spec.department'),
        ),
        migrations.AddField(
            model_name='approvalmatrix',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='spec.doctype'),
        ),
        migrations.CreateModel(
            name='SpecSig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_dt', models.DateTimeField(blank=True, null=True)),
                ('from_am', models.BooleanField(default=False)),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='spec.role')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigs', to='spec.spec')),
            ],
            options={
                'db_table': 'spec_sig',
                'managed': True,
                'unique_together': {('spec', 'role', 'signer')},
            },
        ),
        migrations.CreateModel(
            name='SpecFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=4000)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('seq', models.IntegerField()),
                ('incl_pdf', models.BooleanField(default=False)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='spec.spec')),
            ],
            options={
                'db_table': 'spec_file',
                'managed': True,
                'unique_together': {('spec', 'filename')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='approvalmatrix',
            unique_together={('doc_type', 'department')},
        ),
    ]
