# Generated by Django 4.0.1 on 2022-07-28 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
                ('sub_cat', models.CharField(max_length=50)),
                ('descr', models.CharField(blank=True, max_length=4000, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('confidential', models.BooleanField(blank=True, default=False, null=True)),
                ('file_temp', models.CharField(blank=True, max_length=4000, null=True)),
                ('jira_temp', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
                'unique_together': {('cat', 'sub_cat')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, max_length=4000, null=True)),
                ('any', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('ver', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=4000)),
                ('keywords', models.CharField(max_length=4000)),
                ('state', models.CharField(max_length=50)),
                ('create_dt', models.DateTimeField()),
                ('mod_ts', models.DateTimeField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.category')),
            ],
            options={
                'db_table': 'spec',
                'managed': True,
                'unique_together': {('num', 'ver')},
            },
        ),
        migrations.CreateModel(
            name='SpecReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_spec', models.CharField(max_length=50)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.spec')),
            ],
            options={
                'db_table': 'spec_reference',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpecHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_ts', models.DateTimeField()),
                ('change_type', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=4000)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.spec')),
                ('upd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spec_hist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpecFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('_filename', models.CharField(max_length=4000)),
                ('_uuid', models.CharField(max_length=48)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.spec')),
            ],
            options={
                'db_table': 'spec_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='spec.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.category')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.role')),
            ],
            options={
                'db_table': 'category_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpecSig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_dt', models.DateTimeField(null=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.role')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.spec')),
            ],
            options={
                'db_table': 'spec_sig',
                'managed': True,
                'unique_together': {('spec', 'role', 'signer')},
            },
        ),
    ]
