# Generated by Django 4.0.1 on 2022-08-05 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryReadRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cat_read_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategorySignRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cat_sign_role',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='file_temp',
        ),
        migrations.RemoveField(
            model_name='specreference',
            name='ref_spec',
        ),
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='specreference',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specreference',
            name='ver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specs', to='spec.category'),
        ),
        migrations.AlterField(
            model_name='specfile',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='spec.spec'),
        ),
        migrations.AlterField(
            model_name='spechist',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist', to='spec.spec'),
        ),
        migrations.AlterField(
            model_name='specsig',
            name='delegate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specsig',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='spec.role'),
        ),
        migrations.AlterField(
            model_name='specsig',
            name='signed_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specsig',
            name='signer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specsig',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigs', to='spec.spec'),
        ),
        migrations.DeleteModel(
            name='CategoryRole',
        ),
        migrations.AddField(
            model_name='categorysignrole',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signRoles', to='spec.category'),
        ),
        migrations.AddField(
            model_name='categorysignrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.role'),
        ),
        migrations.AddField(
            model_name='categoryreadrole',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readRoles', to='spec.category'),
        ),
        migrations.AddField(
            model_name='categoryreadrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.role'),
        ),
    ]
