# Generated by Django 4.0.7 on 2022-09-01 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spec', '0002_userdelegate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_watch',
                'managed': True,
            },
        ),
    ]
