# Generated by Django 4.0.1 on 2022-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0002_categoryreadrole_categorysignrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='any',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
