# Generated by Django 4.0.1 on 2022-08-07 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spec', '0003_alter_role_active_alter_role_any'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='specreference',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='spec.spec'),
        ),
        migrations.AlterField(
            model_name='specsig',
            name='delegate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='specfile',
            unique_together={('spec', '_uuid')},
        ),
    ]
