# Generated by Django 4.0.1 on 2022-08-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0004_alter_role_active_alter_specreference_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsig',
            name='from_cat',
            field=models.BooleanField(default=False),
        ),
    ]
