# Generated by Django 4.0.7 on 2022-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0004_alter_userdelegate_delegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='reason',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='jira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
