# Generated by Django 4.0.7 on 2022-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0005_spec_reason_alter_spec_jira'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='sunset_interval',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctype',
            name='sunset_warn',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
