# Generated by Django 4.0.1 on 2022-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0006_alter_specsig_signer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='keywords',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
