# Generated by Django 4.0.7 on 2022-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0006_doctype_sunset_interval_doctype_sunset_warn'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='approved_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='sunset_extended_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
